version: "3.3"
services:
  java:
    build: ./images/java/.
    volumes:
      - ./images/java/resources/app.jar:/usr/app/app.jar

#  database:
#    image: mysql:5.7
#    restart: always
#    command:
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_unicode_ci
#      --explicit_defaults_for_timestamp=1
#      --tls-version=TLSv1.2
#    environment:
#      - MYSQL_ROOT_PASSWORD=qOaeMOiVTehFrVZl2Xjl36UNHee4YCeqjmogv3fk
#      - MYSQL_DATABASE=database
#      - MYSQL_USER=fpasquer
#      - MYSQL_PASSWORD=qKuCsUDVu1zBLTYIiJz273NUTLebsT3Lb2moP0d6ZrjiQRnROk
#      - MYSQL_RANDOM_ROOT_PASSWORD=yes
#      - MYSQL_ONETIME_PASSWORD=yes
#    volumes:
#      - ./images/mysql/database:/var/lib/mysql
#    ports:
#      - '3308:3306'
#
#  phpmyadmin:
#    image: phpmyadmin
#    restart: always
#    ports:
#      - 8081:80
#    environment:
#      - PMA_HOST=database